import{z}from'zod';import{applyManagedPlans}from'./entitlements.js';import{mountAsaasRoutes,asaasConfigured}from'./asaas.js';
const PLAN_IDS=['FREE','DRIVER','PRO','TEAM','BUSINESS'],STATUSES=['INACTIVE','TRIALING','ACTIVE','PAST_DUE','CANCELLED'];
export const configuredAdminEmails=()=>new Set(String(process.env.ADMIN_EMAILS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean));
export const roleForLogin=user=>user.role==='ADMIN'||configuredAdminEmails().has(String(user.email).toLowerCase())?'ADMIN':'USER';
export function adminOnly(req,res,next){const configured=configuredAdminEmails().has(String(req.auth?.email||'').toLowerCase());if(req.auth?.role!=='ADMIN'&&!configured)return res.status(403).json({error:'Acesso administrativo necessário'});if(configured)req.auth.role='ADMIN';next()}
const planInput=z.object({name:z.string().min(2).max(60).optional(),priceCents:z.number().int().min(0).max(100000000).optional(),routesPerMonth:z.number().int().positive().max(1000000).nullable().optional(),stopsPerRoute:z.number().int().positive().max(10000).nullable().optional(),historyDays:z.number().int().positive().max(36500).nullable().optional(),drivers:z.number().int().positive().max(100000).nullable().optional(),active:z.boolean().optional(),featured:z.boolean().optional(),description:z.string().max(500).nullable().optional()});
const userInput=z.object({plan:z.enum(PLAN_IDS).optional(),subscriptionStatus:z.enum(STATUSES).optional(),role:z.enum(['USER','ADMIN']).optional(),billingPeriodEnd:z.string().datetime().nullable().optional()});
export function mountAdminRoutes(app,{db,auth,routingConfigured,billingConfigured}){
 db.planConfig.findMany().then(applyManagedPlans).catch(()=>{});
 mountAsaasRoutes(app,{db,auth,planPrice:async plan=>(await db.planConfig.findUnique({where:{id:plan},select:{priceCents:true}}))?.priceCents||0});
 app.get('/v1/admin/overview',auth,adminOnly,async(req,res)=>{const since=new Date(Date.now()-30*86400000),month=new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth(),1));const[users,activeSubscribers,routes30,deliveries30,failed30,routesMonth,addresses,plans]=await Promise.all([db.user.count(),db.user.count({where:{subscriptionStatus:{in:['ACTIVE','TRIALING']}}}),db.route.count({where:{createdAt:{gte:since}}}),db.delivery.count({where:{createdAt:{gte:since}}}),db.delivery.count({where:{createdAt:{gte:since},status:'FAILED'}}),db.route.count({where:{createdAt:{gte:month}}}),db.address.count(),db.user.groupBy({by:['plan'],_count:{_all:true}})]);res.json({users,activeSubscribers,routes30,deliveries30,failed30,routesMonth,addresses,plans:plans.map(p=>({plan:p.plan,count:p._count._all})),services:{database:true,routing:routingConfigured(),billing:billingConfigured()||asaasConfigured(),asaas:asaasConfigured()},at:new Date().toISOString()})});
 app.get('/v1/admin/users',auth,adminOnly,async(req,res)=>{const q=String(req.query.q||'').trim(),take=Math.min(200,Math.max(1,Number(req.query.take||100)));res.json(await db.user.findMany({where:q?{OR:[{email:{contains:q,mode:'insensitive'}},{name:{contains:q,mode:'insensitive'}}]}:undefined,select:{id:true,name:true,email:true,role:true,plan:true,subscriptionStatus:true,billingPeriodEnd:true,createdAt:true,updatedAt:true,_count:{select:{routes:true,deliveries:true,addresses:true}}},orderBy:{createdAt:'desc'},take}))});
 app.patch('/v1/admin/users/:id',auth,adminOnly,async(req,res)=>{const p=userInput.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Alteração de usuário inválida'});if(req.params.id===req.auth.sub&&p.data.role==='USER')return res.status(400).json({error:'Você não pode remover seu próprio acesso administrativo'});const data={...p.data};if(p.data.billingPeriodEnd!==undefined)data.billingPeriodEnd=p.data.billingPeriodEnd?new Date(p.data.billingPeriodEnd):null;try{res.json(await db.user.update({where:{id:req.params.id},data,select:{id:true,name:true,email:true,role:true,plan:true,subscriptionStatus:true,billingPeriodEnd:true}}))}catch{res.status(404).json({error:'Usuário não encontrado'})}});
 app.get('/v1/admin/plans',auth,adminOnly,async(req,res)=>res.json(await db.planConfig.findMany({orderBy:{priceCents:'asc'}})));
 app.patch('/v1/admin/plans/:id',auth,adminOnly,async(req,res)=>{if(!PLAN_IDS.includes(req.params.id))return res.status(404).json({error:'Plano não encontrado'});const p=planInput.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Configuração de plano inválida'});try{const updated=await db.planConfig.update({where:{id:req.params.id},data:p.data});applyManagedPlans([updated]);res.json(updated)}catch{res.status(404).json({error:'Plano não encontrado'})}});
 app.get('/v1/admin/routes',auth,adminOnly,async(req,res)=>res.json(await db.route.findMany({select:{id:true,status:true,sourceFilename:true,stops:true,deliveriesCount:true,completedStops:true,plannedKm:true,createdAt:true,updatedAt:true,user:{select:{name:true,email:true}}},orderBy:{createdAt:'desc'},take:200})));
 app.get('/v1/admin/deliveries',auth,adminOnly,async(req,res)=>res.json(await db.delivery.findMany({select:{id:true,status:true,packageNo:true,deliveredAt:true,failureReason:true,createdAt:true,user:{select:{name:true,email:true}},address:{select:{address:true,type:true}}},orderBy:{createdAt:'desc'},take:300})));
 app.get('/v1/admin/health',auth,adminOnly,async(req,res)=>{let database=false;try{await db.$queryRaw`SELECT 1`;database=true}catch{}res.status(database?200:503).json({database,routing:routingConfigured(),billing:billingConfigured()||asaasConfigured(),asaas:asaasConfigured(),at:new Date().toISOString()})});
}
