import crypto from'node:crypto';
const PLANS=new Set(['DRIVER','PRO','TEAM','BUSINESS']);
const METHODS=new Set(['PIX','CREDIT_CARD']);
const baseUrl=()=>process.env.ASAAS_ENVIRONMENT==='production'?'https://api.asaas.com/v3':'https://api-sandbox.asaas.com/v3';
export const asaasConfigured=()=>Boolean(process.env.ASAAS_API_KEY);
const safeEqual=(a,b)=>{const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&x.length>0&&crypto.timingSafeEqual(x,y)};
async function asaas(path,{method='GET',body}={}){if(!asaasConfigured())throw new Error('Asaas não configurado');const r=await fetch(`${baseUrl()}${path}`,{method,headers:{'Content-Type':'application/json','User-Agent':'RouteFlow/1.0','access_token':process.env.ASAAS_API_KEY},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(65000)});let data={};try{data=await r.json()}catch{}if(!r.ok){const msg=data?.errors?.map(e=>e.description).filter(Boolean).join('; ')||data?.message||`Asaas HTTP ${r.status}`;const err=new Error(msg);err.status=r.status;err.details=data?.errors||[];throw err}return data}
const addMonth=d=>{const x=new Date(d);x.setUTCMonth(x.getUTCMonth()+1);return x};
const isoDateTime=d=>new Date(d).toISOString().slice(0,19).replace('T',' ');
const planFromRef=ref=>{const m=/^routeflow:([^:]+):(DRIVER|PRO|TEAM|BUSINESS)(?::(?:PIX|CREDIT_CARD))?$/i.exec(String(ref||''));return m?{userId:m[1],plan:m[2].toUpperCase()}:null};
const externalRef=o=>o?.externalReference||o?.external_reference||o?.checkout?.externalReference||o?.payment?.externalReference||o?.subscription?.externalReference||'';
async function ensureWebhook(){if(!asaasConfigured()||!process.env.ASAAS_WEBHOOK_TOKEN)return;const url=process.env.ASAAS_WEBHOOK_URL||'https://routeflow-api-tz5q.onrender.com/v1/billing/asaas/webhook';const existing=await asaas('/webhooks');const rows=existing?.data||existing||[];if(Array.isArray(rows)&&rows.some(x=>x.url===url))return;const email=String(process.env.ADMIN_EMAILS||'').split(',')[0]?.trim()||'evandroccj@gmail.com';await asaas('/webhooks',{method:'POST',body:{name:'RouteFlow Billing',url,email,enabled:true,interrupted:false,apiVersion:3,authToken:process.env.ASAAS_WEBHOOK_TOKEN,sendType:'SEQUENTIALLY',events:['CHECKOUT_PAID','CHECKOUT_CANCELED','CHECKOUT_EXPIRED','SUBSCRIPTION_CREATED','PAYMENT_RECEIVED','PAYMENT_CONFIRMED','PAYMENT_OVERDUE','PAYMENT_REFUNDED','PAYMENT_DELETED']}})}
export function mountAsaasRoutes(app,{db,auth,planPrice}){
 ensureWebhook().then(()=>console.log(JSON.stringify({level:'info',type:'asaas_webhook_ready'}))).catch(e=>console.error(JSON.stringify({level:'error',type:'asaas_webhook_provision',message:e.message})));
 app.get('/v1/billing/asaas/status',auth,(req,res)=>res.json({configured:asaasConfigured(),environment:process.env.ASAAS_ENVIRONMENT==='production'?'production':'sandbox',provider:'asaas',methods:['PIX','CREDIT_CARD']}));
 app.post('/v1/billing/asaas/checkout',auth,async(req,res)=>{try{const plan=String(req.body?.plan||'').toUpperCase(),paymentMethod=String(req.body?.paymentMethod||'CREDIT_CARD').toUpperCase();if(!PLANS.has(plan))return res.status(400).json({error:'Plano inválido'});if(!METHODS.has(paymentMethod))return res.status(400).json({error:'Forma de pagamento inválida'});const price=Number(await planPrice(plan));if(!(price>0))return res.status(400).json({error:'Preço do plano não configurado'});const origin=String(process.env.PUBLIC_APP_URL||'https://turlang.github.io/routeflow/').replace(/\/$/,'');const ref=`routeflow:${req.auth.sub}:${plan}:${paymentMethod}`,now=new Date(),common={billingTypes:[paymentMethod],minutesToExpire:60,externalReference:ref,callback:{successUrl:`${origin}/?billing=success`,cancelUrl:`${origin}/?billing=cancel`,expiredUrl:`${origin}/?billing=expired`},items:[{name:`RouteFlow ${plan}`,description:`Plano RouteFlow ${plan}`,quantity:1,value:Number((price/100).toFixed(2))}]};const payload=paymentMethod==='PIX'?{...common,chargeTypes:['DETACHED']}:{...common,chargeTypes:['RECURRENT'],subscription:{cycle:'MONTHLY',nextDueDate:isoDateTime(now)}};const checkout=await asaas('/checkouts',{method:'POST',body:payload});const id=checkout.id;if(!id)throw new Error('Asaas não retornou o checkout');const url=checkout.link||`https://asaas.com/checkoutSession/show?id=${encodeURIComponent(id)}`;await db.billingCheckout.upsert({where:{providerId:id},update:{status:'ACTIVE',plan,url},create:{providerId:id,userId:req.auth.sub,plan,status:'ACTIVE',url}});res.status(201).json({id,url,plan,paymentMethod,recurring:paymentMethod==='CREDIT_CARD',environment:process.env.ASAAS_ENVIRONMENT==='production'?'production':'sandbox'})}catch(e){console.error(JSON.stringify({level:'warn',type:'asaas_checkout_rejected',status:e.status||502,message:e.message,details:e.details||[]}));res.status(e.status&&e.status<500?e.status:502).json({error:e.message||'Falha ao criar checkout Asaas'})}});
 app.post('/v1/billing/asaas/webhook',async(req,res)=>{const expected=process.env.ASAAS_WEBHOOK_TOKEN;if(!expected||!safeEqual(req.headers['asaas-access-token'],expected))return res.status(401).json({error:'Webhook Asaas não autorizado'});const eventId=String(req.body?.id||'').trim(),event=String(req.body?.event||'').trim().toUpperCase();if(!eventId||!event)return res.status(400).json({error:'Evento Asaas inválido'});try{if(await db.billingEvent.findUnique({where:{providerEventId:eventId}}))return res.json({ok:true,duplicate:true});await db.billingEvent.create({data:{providerEventId:eventId,type:event,payload:req.body}});const object=req.body.checkout||req.body.subscription||req.body.payment||{},ref=externalRef(req.body),parsed=planFromRef(ref);if(parsed){if(event==='CHECKOUT_PAID'||event==='PAYMENT_RECEIVED'||event==='PAYMENT_CONFIRMED'){await db.user.updateMany({where:{id:parsed.userId},data:{plan:parsed.plan,subscriptionStatus:'ACTIVE',billingPeriodEnd:addMonth(new Date())}})}if(event==='SUBSCRIPTION_CREATED'&&object.id){await db.billingSubscription.upsert({where:{providerId:object.id},update:{plan:parsed.plan,status:'ACTIVE'},create:{providerId:object.id,userId:parsed.userId,plan:parsed.plan,status:'ACTIVE'}})}if(event==='CHECKOUT_CANCELED'||event==='CHECKOUT_EXPIRED')await db.billingCheckout.updateMany({where:{userId:parsed.userId,plan:parsed.plan,status:'ACTIVE'},data:{status:event.replace('CHECKOUT_','')}})}else if(req.body.payment?.subscription&&['PAYMENT_RECEIVED','PAYMENT_CONFIRMED','PAYMENT_OVERDUE','PAYMENT_REFUNDED','PAYMENT_DELETED'].includes(event)){const sub=await db.billingSubscription.findUnique({where:{providerId:req.body.payment.subscription}});if(sub){if(['PAYMENT_RECEIVED','PAYMENT_CONFIRMED'].includes(event)){await db.user.update({where:{id:sub.userId},data:{plan:sub.plan,subscriptionStatus:'ACTIVE',billingPeriodEnd:addMonth(new Date())}});await db.billingSubscription.update({where:{providerId:sub.providerId},data:{status:'ACTIVE'}})}else if(event==='PAYMENT_OVERDUE'){await db.user.update({where:{id:sub.userId},data:{subscriptionStatus:'PAST_DUE'}});await db.billingSubscription.update({where:{providerId:sub.providerId},data:{status:'PAST_DUE'}})}else if(['PAYMENT_REFUNDED','PAYMENT_DELETED'].includes(event)){await db.user.update({where:{id:sub.userId},data:{subscriptionStatus:'CANCELLED'}});await db.billingSubscription.update({where:{providerId:sub.providerId},data:{status:'CANCELLED'}})}}}res.json({ok:true})}catch(e){console.error(JSON.stringify({level:'error',type:'asaas_webhook',eventId,event,message:e.message}));res.status(500).json({error:'Falha ao processar webhook Asaas'})}});
 app.get('/v1/billing/asaas/history',auth,async(req,res)=>res.json(await db.billingCheckout.findMany({where:{userId:req.auth.sub},orderBy:{createdAt:'desc'},take:50})));
}
