import https from'node:https';import fs from'node:fs';import crypto from'node:crypto';
import{paymentPrices}from'./payment-pricing.js';
const PLANS=new Set(['DRIVER','PRO','TEAM','BUSINESS']);
const sandbox=()=>process.env.INTER_ENVIRONMENT!=='production';
const host=()=>sandbox()?'cdpj-sandbox.partners.uatinter.co':'cdpj.partners.bancointer.com.br';
const fileOrPem=name=>{const raw=process.env[name];if(!raw)return null;if(raw.includes('BEGIN '))return raw.replace(/\\n/g,'\n');try{return fs.readFileSync(raw)}catch{return null}};
const base64Value=name=>{const raw=process.env[name];if(!raw)return null;try{return Buffer.from(raw.replace(/\s/g,''),'base64')}catch{return null}};
const certificate=()=>base64Value('INTER_CERT_BASE64')||fileOrPem('INTER_CERTIFICATE');
const privateKey=()=>base64Value('INTER_KEY_BASE64')||fileOrPem('INTER_PRIVATE_KEY');
export const interAuthConfigured=()=>Boolean(process.env.INTER_CLIENT_ID&&process.env.INTER_CLIENT_SECRET&&certificate()&&privateKey());
export const interConfigured=()=>Boolean(interAuthConfigured()&&process.env.INTER_PIX_KEY);
let tokenCache={token:null,expires:0};
function request(path,{method='GET',headers={},body,form=false}={}){return new Promise((resolve,reject)=>{const cert=certificate(),key=privateKey();if(!cert||!key)return reject(new Error('Certificado Inter não configurado'));const payload=body===undefined?null:form?new URLSearchParams(body).toString():JSON.stringify(body);const req=https.request({hostname:host(),path,method,cert,key,headers:{Accept:'application/json',...(payload?{'Content-Type':form?'application/x-www-form-urlencoded':'application/json','Content-Length':Buffer.byteLength(payload)}:{}),...headers},timeout:30000},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>{let data={};try{data=raw?JSON.parse(raw):{}}catch{data={raw}}if(res.statusCode>=200&&res.statusCode<300)return resolve(data);const e=new Error(data?.detail||data?.title||data?.message||`Inter HTTP ${res.statusCode}`);e.status=res.statusCode;e.details=data;reject(e)})});req.on('timeout',()=>req.destroy(new Error('Timeout Banco Inter')));req.on('error',reject);if(payload)req.write(payload);req.end()})}
async function token(){if(tokenCache.token&&Date.now()<tokenCache.expires-60000)return tokenCache.token;const scope=process.env.INTER_SCOPES||'cob.write cob.read pix.read webhook.read webhook.write';const data=await request('/oauth/v2/token',{method:'POST',form:true,body:{client_id:process.env.INTER_CLIENT_ID,client_secret:process.env.INTER_CLIENT_SECRET,scope,grant_type:'client_credentials'}});if(!data.access_token)throw new Error('Inter não retornou access token');tokenCache={token:data.access_token,expires:Date.now()+Number(data.expires_in||3600)*1000};return tokenCache.token}
async function inter(path,opts={}){const access=await token(),account=String(process.env.INTER_ACCOUNT||'').replace(/\D/g,'');return request(path,{...opts,headers:{Authorization:`Bearer ${access}`,...(account?{'x-conta-corrente':account}:{}),...(opts.headers||{})}})}
const txid=()=>crypto.randomBytes(16).toString('hex');
const addMonth=d=>{const x=new Date(d);x.setUTCMonth(x.getUTCMonth()+1);return x};
const webhookUrl=()=>`${String(process.env.PUBLIC_API_URL||'https://routeflow-api-tz5q.onrender.com').replace(/\/$/,'')}/v1/billing/inter/webhook`;
async function activatePix(db,pix){const id=String(pix?.txid||'');if(!id)return false;const checkout=await db.billingCheckout.findUnique({where:{providerId:id}});if(!checkout||checkout.status==='PAID')return false;const eventId=`inter:${pix.endToEndId||pix.endToEnd||id}`;if(await db.billingEvent.findUnique({where:{providerEventId:eventId}}))return false;const user=await db.user.findUnique({where:{id:checkout.userId},select:{billingPeriodEnd:true}});const now=new Date(),current=user?.billingPeriodEnd?new Date(user.billingPeriodEnd):null,base=current&&current>now?current:now;await db.$transaction([db.billingEvent.create({data:{providerEventId:eventId,type:'INTER_PIX_RECEIVED',payload:pix}}),db.billingCheckout.update({where:{providerId:id},data:{status:'PAID'}}),db.user.update({where:{id:checkout.userId},data:{plan:checkout.plan,subscriptionStatus:'ACTIVE',billingPeriodEnd:addMonth(base)}})]);return true}
export function mountInterRoutes(app,{db,auth,planPrice}){
 app.get('/v1/billing/inter/status',auth,async(req,res)=>{const authConfigured=interAuthConfigured();let authenticated=false,error=null,webhook=null;if(authConfigured){try{await token();authenticated=true;if(interConfigured()){try{webhook=await inter(`/pix/v2/webhook/${encodeURIComponent(process.env.INTER_PIX_KEY)}`)}catch{webhook=null}}}catch(e){error=e.message||'Falha na autenticação Inter'}}res.json({configured:interConfigured(),authConfigured,authenticated,pixKeyConfigured:Boolean(process.env.INTER_PIX_KEY),webhookConfigured:Boolean(webhook?.webhookUrl),webhookUrl:webhook?.webhookUrl||null,expectedWebhookUrl:webhookUrl(),environment:sandbox()?'sandbox':'production',provider:'inter',method:'PIX',automaticPixSupported:false,...(error?{error}:{})})});
 app.post('/v1/billing/inter/webhook/setup',auth,async(req,res)=>{try{if(!interConfigured())return res.status(503).json({error:'Pix Banco Inter ainda não configurado'});const result=await inter(`/pix/v2/webhook/${encodeURIComponent(process.env.INTER_PIX_KEY)}`,{method:'PUT',body:{webhookUrl:webhookUrl()}});res.json({ok:true,webhookUrl:webhookUrl(),result})}catch(e){res.status(e.status&&e.status<500?e.status:502).json({error:e.message||'Falha ao configurar webhook Inter'})}});
 app.get('/v1/billing/pricing',auth,async(req,res)=>{const rows=await db.planConfig.findMany({where:{active:true},orderBy:{priceCents:'asc'}});res.json(rows.map(p=>({id:p.id,name:p.name,...paymentPrices(p.priceCents)})))});
 app.post('/v1/billing/inter/pix',auth,async(req,res)=>{try{if(!interConfigured())return res.status(503).json({error:'Pix Banco Inter ainda não configurado'});const plan=String(req.body?.plan||'').toUpperCase();if(!PLANS.has(plan))return res.status(400).json({error:'Plano inválido'});const base=Number(await planPrice(plan));if(!(base>0))return res.status(400).json({error:'Preço do plano não configurado'});const price=paymentPrices(base).pixCents,id=txid(),ref=`routeflow:${req.auth.sub}:${plan}:INTER_PIX`;const payload={calendario:{expiracao:3600},valor:{original:(price/100).toFixed(2)},chave:process.env.INTER_PIX_KEY,solicitacaoPagador:`RouteFlow ${plan} - ${ref}`};const cob=await inter(`/pix/v2/cob/${id}`,{method:'PUT',body:payload});const providerId=cob.txid||id;await db.billingCheckout.upsert({where:{providerId},update:{status:'ACTIVE',plan,url:cob.pixCopiaECola||cob.location||null},create:{providerId,userId:req.auth.sub,plan,status:'ACTIVE',url:cob.pixCopiaECola||cob.location||null}});res.status(201).json({provider:'inter',plan,txid:providerId,amountCents:price,pixCopiaECola:cob.pixCopiaECola||null,location:cob.location||cob.loc?.location||null,expiresInSeconds:Number(cob.calendario?.expiracao||3600),environment:sandbox()?'sandbox':'production'})}catch(e){console.error(JSON.stringify({level:'warn',type:'inter_pix_rejected',status:e.status||502,message:e.message}));res.status(e.status&&e.status<500?e.status:502).json({error:e.message||'Falha ao criar Pix Banco Inter'})}});
 app.post('/v1/billing/inter/webhook',async(req,res)=>{try{const items=Array.isArray(req.body?.pix)?req.body.pix:Array.isArray(req.body)?req.body:[];let activated=0;for(const pix of items)if(await activatePix(db,pix))activated++;res.json({ok:true,received:items.length,activated})}catch(e){console.error(JSON.stringify({level:'error',type:'inter_pix_webhook',message:e.message}));res.status(500).json({error:'Falha ao processar webhook Inter'})}});
}
