import{apiBase,setApiBase,authUser,hasSession,saveSession,clearSession,register,login,me}from'./api.js';
import{pullAddresses}from'./sync.js';
const $=id=>document.getElementById(id);
function mount(){const host=document.createElement('div');host.className='account-shell';host.innerHTML=`<button id="accountToggle" class="account-toggle" type="button">Conta</button><section id="accountPanel" class="account-panel" hidden><div class="account-head"><div><b>RouteFlow Cloud</b><small id="apiState">Modo local</small></div><button id="accountClose" class="secondary" type="button">Fechar</button></div><div class="account-config"><label>API RouteFlow<input id="apiUrl" type="url" placeholder="https://api.seudominio.com"></label><button id="saveApi" type="button">Conectar API</button></div><div id="accountGuest"><label>Nome<input id="accountName" autocomplete="name" placeholder="Seu nome"></label><label>E-mail<input id="accountEmailInput" type="email" autocomplete="email" placeholder="voce@email.com"></label><label>Senha<input id="accountPassword" type="password" autocomplete="current-password" minlength="8" placeholder="Mínimo 8 caracteres"></label><div class="account-actions"><button id="loginAccount" type="button">Entrar</button><button id="createAccount" class="secondary" type="button">Criar conta</button></div></div><div id="accountSigned" hidden><strong id="accountUser"></strong><span id="accountEmail"></span><button id="logoutAccount" class="secondary" type="button">Sair</button></div><p id="accountMessage" class="account-message"></p></section>`;document.querySelector('header')?.insertBefore(host,$('status'));return host}
function setMessage(text,error=false){const el=$('accountMessage');if(!el)return;el.textContent=text||'';el.classList.toggle('error',error)}
function render(){const user=authUser(),signed=hasSession();$('accountGuest').hidden=signed;$('accountSigned').hidden=!signed;if(signed){$('accountUser').textContent=user?.name||user?.email||'Usuário';$('accountEmail').textContent=user?.email||''}$('apiUrl').value=apiBase();$('apiState').textContent=apiBase()?'API configurada':'Modo local';$('accountToggle').textContent=signed?(user?.name||'Conta'):'Conta'}
async function syncCloud(){try{const r=await pullAddresses();if(r.mode==='cloud')setMessage(`Conta conectada · ${r.count} endereço(s) sincronizado(s).`)}catch(e){setMessage(`Conta conectada, mas a sincronização falhou: ${e.message}`,true)}}
async function submit(mode){const email=$('accountEmailInput').value.trim(),password=$('accountPassword').value,name=$('accountName').value.trim();if(!apiBase())return setMessage('Configure primeiro o endereço da API.',true);if(!email||!password)return setMessage('Informe e-mail e senha.',true);setMessage(mode==='register'?'Criando conta…':'Entrando…');try{const data=mode==='register'?await register({name:name||undefined,email,password}):await login({email,password});saveSession(data);render();setMessage('Conta conectada. Sincronizando…');await syncCloud()}catch(e){setMessage(e.message,true)}}
export function initAuthUI(){mount();$('accountToggle').addEventListener('click',()=>{$('accountPanel').hidden=!$('accountPanel').hidden});$('accountClose').addEventListener('click',()=>{$('accountPanel').hidden=true});$('saveApi').addEventListener('click',()=>{const value=$('apiUrl').value.trim();if(!/^https?:\/\//i.test(value))return setMessage('Informe uma URL válida da API.',true);setApiBase(value);render();setMessage('API configurada.');});$('createAccount').addEventListener('click',()=>submit('register'));$('loginAccount').addEventListener('click',()=>submit('login'));$('logoutAccount').addEventListener('click',()=>{clearSession();render();setMessage('Sessão encerrada. O modo local continua disponível.');});render();if(hasSession()&&apiBase())me().then(async user=>{saveSession({token:localStorage.getItem('routeflow.authToken.v1'),user});render();await syncCloud()}).catch(()=>{render();setMessage('A sessão precisa ser renovada.',true)})}
