export function normalizeStreet(value='') {
  return String(value).split(',')[0].normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
    .replace(/^(r\.?|rua|av\.?|avenida|trav\.?|travessa|al\.?|alameda|estr\.?|estrada|rod\.?|rodovia)\s+/,'').replace(/\s+/g,' ').trim();
}
export function coordinateIssue(row){const lat=Number(row?.Latitude),lon=Number(row?.Longitude),address=String(row?.['Destination Address']||'').trim();if(!Number.isFinite(lat)||!Number.isFinite(lon))return'Coordenadas ausentes ou inválidas';if(lat<-90||lat>90||lon<-180||lon>180)return'Coordenadas fora dos limites geográficos';if(Math.abs(lat)<0.00001&&Math.abs(lon)<0.00001)return'Coordenadas apontam para 0,0';if(!address)return'Endereço de destino ausente';return''}
export function validateDeliveryRows(rows=[]){const issues=[];rows.forEach((row,index)=>{const issue=coordinateIssue(row);if(issue)issues.push({index,row:index+2,address:String(row?.['Destination Address']||''),issue})});return{valid:issues.length===0,issues,total:rows.length,validRows:rows.length-issues.length}}
export function groupStops(rows) {
  const map=new Map();
  rows.forEach((row,index)=>{if(coordinateIssue(row))return;const lat=Number(row.Latitude),lon=Number(row.Longitude);const key=`${lat.toFixed(5)}|${lon.toFixed(5)}`;if(!map.has(key))map.set(key,{key,lat,lon,street:normalizeStreet(row['Destination Address']),address:row['Destination Address']||'',neighborhood:row.Bairro||'',city:row.City||'',zipcode:row['Zipcode/Postal code']||'',rows:[],firstIndex:index});map.get(key).rows.push({...row,__sourceIndex:index})});
  return [...map.values()];
}
export function haversine(a,b){const rad=x=>x*Math.PI/180,R=6371000,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon);const q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
export function fallbackMatrix(stops){return stops.map(a=>stops.map(b=>haversine(a,b)));}
function edge(matrix,a,b){const v=matrix?.[a]?.[b];return Number.isFinite(v)?v:Infinity;}
function optionsFrom(value){if(typeof value==='number')return{mode:'distance',streetPenalty:value};const o=value&&typeof value==='object'?value:{};return{mode:o.mode||'distance',streetPenalty:Number(o.streetPenalty||0),reentryPenalty:Number(o.reentryPenalty||0),backtrackPenalty:Number(o.backtrackPenalty||0),circularWeight:Number(o.circularWeight||0)};}
function routeAxis(stops,start){const origin=stops[start];if(!origin||stops.length<2)return{x:1,y:0};let far=start,dist=-1;for(let i=0;i<stops.length;i++){const d=haversine(origin,stops[i]);if(d>dist){dist=d;far=i}}const target=stops[far],latScale=Math.cos((origin.lat+target.lat)*Math.PI/360),x=(target.lon-origin.lon)*latScale,y=target.lat-origin.lat,n=Math.hypot(x,y)||1;return{x:x/n,y:y/n};}
function projection(stop,origin,axis){const latScale=Math.cos((origin.lat+stop.lat)*Math.PI/360);return(stop.lon-origin.lon)*latScale*axis.x+(stop.lat-origin.lat)*axis.y;}
function routeCost(order,matrix,stops,rawOptions=0){if(order.length<2)return 0;const opt=optionsFrom(rawOptions),origin=stops[order[0]],axis=routeAxis(stops,order[0]);let cost=0,prevStreet=stops[order[0]]?.street||'',maxProgress=-Infinity;const left=new Set();for(let k=1;k<order.length;k++){const a=order[k-1],b=order[k],leg=edge(matrix,a,b);if(!Number.isFinite(leg))return Infinity;cost+=leg;const street=stops[b]?.street||'';if(street!==prevStreet){if(prevStreet)left.add(prevStreet);if(street&&left.has(street)){const base=opt.reentryPenalty||opt.streetPenalty;cost+=base*(opt.mode==='progressive'?1+left.size*.08:1)}prevStreet=street}if(opt.mode==='progressive'){const p=projection(stops[b],origin,axis);if(maxProgress>-Infinity&&p<maxProgress){const regression=maxProgress-p;cost+=(opt.backtrackPenalty||18000)*Math.min(4,1+regression*700)}maxProgress=Math.max(maxProgress,p)}}if(opt.mode==='circular'){const back=edge(matrix,order[order.length-1],order[0]);if(Number.isFinite(back))cost+=back*(opt.circularWeight||1)}return cost;}
function greedySeed(stops,matrix,start,opt,second=null){const remaining=new Set(stops.map((_,i)=>i)),order=[start];remaining.delete(start);if(second!=null&&remaining.has(second)){order.push(second);remaining.delete(second)}while(remaining.size){const cur=order[order.length-1];let best=-1,bestCost=Infinity;for(const i of remaining){const candidate=[...order,i],cost=routeCost(candidate,matrix,stops,opt);if(cost<bestCost){bestCost=cost;best=i}}if(best<0)throw new Error('Não existe percurso viário permitido para alcançar todas as paradas a partir deste ponto.');order.push(best);remaining.delete(best)}return order;}
function improveRelocate(seed,matrix,stops,opt){let order=[...seed],bestCost=routeCost(order,matrix,stops,opt),changed=true,passes=0;while(changed&&passes++<18){changed=false;outer:for(let from=1;from<order.length;from++){for(let to=1;to<order.length;to++){if(from===to)continue;const candidate=[...order],node=candidate.splice(from,1)[0];candidate.splice(to,0,node);const cost=routeCost(candidate,matrix,stops,opt);if(cost+0.5<bestCost){order=candidate;bestCost=cost;changed=true;break outer}}}}return order;}
function improveSwap(seed,matrix,stops,opt){let order=[...seed],bestCost=routeCost(order,matrix,stops,opt),changed=true,passes=0;while(changed&&passes++<8){changed=false;outer:for(let a=1;a<order.length-1;a++){for(let b=a+1;b<order.length;b++){const candidate=[...order];[candidate[a],candidate[b]]=[candidate[b],candidate[a]];const cost=routeCost(candidate,matrix,stops,opt);if(cost+0.5<bestCost){order=candidate;bestCost=cost;changed=true;break outer}}}}return order;}
function improveTwoOpt(seed,matrix,stops,opt){let order=[...seed],bestCost=routeCost(order,matrix,stops,opt),passes=0,changed=true;while(changed&&passes++<8){changed=false;outer:for(let i=1;i<order.length-2;i++){for(let j=i+1;j<order.length-1;j++){const candidate=[...order.slice(0,i),...order.slice(i,j+1).reverse(),...order.slice(j+1)],cost=routeCost(candidate,matrix,stops,opt);if(cost+0.5<bestCost){order=candidate;bestCost=cost;changed=true;break outer}}}}return order;}
function improve(seed,matrix,stops,opt){return improveSwap(improveTwoOpt(improveRelocate(seed,matrix,stops,opt),matrix,stops,opt),matrix,stops,opt);}
export function optimizeOrder(stops,matrix,startIndex=0,rawOptions=0){if(!stops.length)return[];const start=Math.max(0,Math.min(startIndex,stops.length-1)),opt=optionsFrom(rawOptions);let best=improve(greedySeed(stops,matrix,start,opt),matrix,stops,opt),bestCost=routeCost(best,matrix,stops,opt);const candidates=stops.map((_,i)=>i).filter(i=>i!==start&&Number.isFinite(edge(matrix,start,i))).sort((a,b)=>edge(matrix,start,a)-edge(matrix,start,b)).slice(0,Math.min(24,stops.length-1));for(const second of candidates){const candidate=improve(greedySeed(stops,matrix,start,opt,second),matrix,stops,opt),cost=routeCost(candidate,matrix,stops,opt);if(cost<bestCost){best=candidate;bestCost=cost}}if(!Number.isFinite(bestCost))throw new Error('Não foi encontrada uma rota viária válida respeitando os sentidos permitidos.');return best;}
export function flattenRoute(stops,order){let deliverySeq=1;return order.flatMap((idx,stopNo)=>stops[idx].rows.map(row=>{const{__sourceIndex,...original}=row;return{...original,'Optimized Sequence':deliverySeq++,'Optimized Stop':stopNo+1}}));}
export function routeMetrics(order,matrix,stops){let distance=0,reentries=0,transitions=0,maxLeg=0;const left=new Set();let prev=stops[order[0]]?.street||'';for(let k=1;k<order.length;k++){const leg=edge(matrix,order[k-1],order[k]);if(!Number.isFinite(leg))return{distance:Infinity,reentries,transitions,maxLeg:Infinity};distance+=leg;maxLeg=Math.max(maxLeg,leg);const s=stops[order[k]].street;if(s!==prev){transitions++;if(prev)left.add(prev);if(s&&left.has(s))reentries++;prev=s}}return{distance,reentries,transitions,maxLeg};}
