import{groupStops,fallbackMatrix,optimizeOrder,flattenRoute,routeMetrics}from'./core.js';
const $=id=>document.getElementById(id);let rows=[],headers=[],stops=[],matrix=[],order=[],filename='',map,markers=[],routeLine,optimizedRows=[];
function setStatus(t){$('status').textContent=t}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initMap(){if(map)return;map=L.map('map').setView([-23.55,-46.63],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map)}
function numberedIcon(n,count){return L.divIcon({className:'stop-wrap',html:`<div class="stop-pin">${n}</div>${count>1?`<span class="stop-count">${count}</span>`:''}`,iconSize:[34,42],iconAnchor:[17,38],tooltipAnchor:[0,-34]})}
function drawPoints(){initMap();markers.forEach(m=>m.remove());markers=[];const seq=order.length?order:stops.map((_,i)=>i);seq.forEach((idx,n)=>{const s=stops[idx],r=s.rows[0];const m=L.marker([s.lat,s.lon],{icon:numberedIcon(n+1,s.rows.length)}).bindTooltip(`<b>Parada ${n+1}</b><br>${esc(s.address)}<br>${esc(r.Bairro||'')}<br>${s.rows.length} entrega(s)`,{direction:'top'});m.addTo(map);markers.push(m)});if(stops.length)map.fitBounds(L.latLngBounds(stops.map(s=>[s.lat,s.lon])).pad(.12))}
function cleanRow(r){const o={};for(const h of headers)o[h]=r[h]??'';return o}
function displayRows(){const seq=order.length?order:stops.map((_,i)=>i);const out=[];seq.forEach((idx,stopNo)=>stops[idx].rows.forEach((r,deliveryAtStop)=>out.push({routeStop:stopNo+1,deliveryAtStop:deliveryAtStop+1,count:stops[idx].rows.length,row:cleanRow(r)})));return out}
function render(){const data=displayRows();$('thead').innerHTML='<th>Rota</th><th>Entrega no ponto</th>'+headers.map(h=>`<th>${esc(h)}</th>`).join('');$('tbody').innerHTML=data.map(x=>`<tr><td class="stopnum"><b>${x.routeStop}</b></td><td>${x.deliveryAtStop}/${x.count}</td>${headers.map(h=>`<td>${esc(x.row[h])}</td>`).join('')}</tr>`).join('')}
async function loadFile(file){setStatus('Lendo Excel…');filename=file.name;const wb=XLSX.read(await file.arrayBuffer());const sheet=wb.Sheets[wb.SheetNames[0]];const aoa=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:true});headers=(aoa[0]||[]).map(String);rows=XLSX.utils.sheet_to_json(sheet,{defval:'',raw:true});stops=groupStops(rows);order=[];matrix=[];optimizedRows=[];$('workspace').hidden=false;$('deliveries').textContent=rows.length;$('stops').textContent=stops.length;$('streets').textContent=new Set(stops.map(s=>s.street)).size;$('reentries').textContent='-';$('export').disabled=true;$('start').innerHTML=stops.map((s,i)=>`<option value="${i}">${i+1}. ${esc(s.address)}</option>`).join('');drawPoints();render();$('notice').textContent=`${rows.length} entregas em ${stops.length} paradas. Todas as ${headers.length} colunas originais da planilha estão na tabela, inclusive Sequence e Stop.`;setStatus('Planilha carregada');setTimeout(()=>map.invalidateSize(),50)}
async function roadMatrix(){const coords=stops.map(s=>`${s.lon},${s.lat}`).join(';');const res=await fetch(`https://router.project-osrm.org/table/v1/driving/${coords}?annotations=distance,duration`);if(!res.ok)throw new Error('Serviço de malha viária indisponível');const data=await res.json();if(data.code!=='Ok'||!data.distances)throw new Error('Não foi possível calcular a matriz viária');const fallback=fallbackMatrix(stops);return data.distances.map((row,i)=>row.map((v,j)=>v??fallback[i][j]*1.35))}
async function drawRoadRoute(){if(routeLine){routeLine.remove();routeLine=null}drawPoints();const pts=order.map(i=>stops[i]);if(pts.length<2)return;const coords=pts.map(s=>`${s.lon},${s.lat}`).join(';');try{const res=await fetch(`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson&steps=false&continue_straight=true`);const data=await res.json();if(data.routes?.[0]){routeLine=L.geoJSON(data.routes[0].geometry,{style:{weight:5,opacity:.72}}).addTo(map);routeLine.bringToBack();map.fitBounds(routeLine.getBounds().pad(.08));$('routeSummary').textContent=`${(data.routes[0].distance/1000).toFixed(1)} km · ${Math.round(data.routes[0].duration/60)} min estimados de deslocamento.`;return}}catch{}$('routeSummary').textContent='Sequência otimizada; geometria detalhada indisponível.'}
async function optimize(){if(!stops.length)return;setStatus('Otimizando…');$('optimize').disabled=true;$('notice').textContent='Buscando o percurso mais contínuo possível pela malha viária…';let source='malha viária real';try{matrix=await roadMatrix()}catch(e){matrix=fallbackMatrix(stops);source='distância geográfica de contingência'}const start=Number($('start').value)||0,penalty=Number($('penalty').value)||0;order=optimizeOrder(stops,matrix,start,penalty);optimizedRows=flattenRoute(stops,order);const m=routeMetrics(order,matrix,stops);$('reentries').textContent=m.reentries;render();await drawRoadRoute();$('notice').textContent=`Rota linear calculada pela ${source}: ${(m.distance/1000).toFixed(2)} km na matriz. Maior salto entre duas paradas: ${(m.maxLeg/1000).toFixed(2)} km. As paradas foram renumeradas no mapa e na tabela.`;$('export').disabled=false;$('optimize').disabled=false;setStatus('Rota pronta')}
function exportExcel(){const flat=optimizedRows.length?optimizedRows:flattenRoute(stops,order.length?order:stops.map((_,i)=>i));const out=flat.map(r=>{const o={'Optimized Sequence':r['Optimized Sequence'],'Optimized Stop':r['Optimized Stop']};for(const h of headers)o[h]=r[h]??'';return o});const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(out);ws['!autofilter']={ref:ws['!ref']};ws['!cols']=Object.keys(out[0]||{}).map(h=>({wch:Math.min(48,Math.max(12,h.length+2,...out.slice(0,100).map(r=>String(r[h]??'').length+2)))}));XLSX.utils.book_append_sheet(wb,ws,'Rota Otimizada');const m=routeMetrics(order,matrix,stops),summary=[['RouteFlow - Resumo'],['Arquivo original',filename],['Entregas',rows.length],['Paradas físicas',stops.length],['Colunas originais',headers.length],['Ruas',new Set(stops.map(s=>s.street)).size],['Distância matriz (km)',(m.distance/1000).toFixed(2)],['Maior trecho (km)',(m.maxLeg/1000).toFixed(2)],['Retornos a ruas',m.reentries]];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(summary),'Resumo');XLSX.writeFile(wb,`routeflow-otimizado-${filename.replace(/\.xlsx?$/i,'')}.xlsx`)}
$('file').addEventListener('change',e=>e.target.files[0]&&loadFile(e.target.files[0]).catch(err=>{setStatus('Erro');$('notice').textContent=err.message}));$('optimize').addEventListener('click',optimize);$('export').addEventListener('click',exportExcel);initMap();
