import{groupStops,optimizeOrder,flattenRoute}from'./core.js';
import{routingTable,routingRoute}from'./api.js';
import{initAuthUI}from'./auth-ui.js';
import{syncImportedStops}from'./sync.js';
import{initDeliveryHistoryUI,recordStopDeliveries}from'./delivery-history-ui.js';
import{initRegistryUI}from'./registry-ui.js';
import{initMobileUI}from'./mobile-ui.js';
import{initRouteHistoryUI}from'./route-history-ui.js';
import{beginRoute,markRouteProgress,finishRoute,resumableRoute,syncActiveRoute}from'./route-session.js';
const $=id=>document.getElementById(id);let rows=[],headers=[],selectedHeaders=[],stops=[],matrix=[],order=[],filename='',map,markers=[],routeLine,optimizedRows=[],routeStats=null,currentLocation=null,dragFrom=null,navigationIndex=0,navMap=null,navLine=null,navMarker=null,navStopMarkers=[],navWatch=null,lastRerouteAt=0,lastNavPosition=null,resumeMode=false,proofStatus='DELIVERED';const SERVICE_MINUTES=3,ARRIVAL_METERS=45,REROUTE_COOLDOWN=12000;
function setStatus(t){$('status').textContent=t}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}function fmtDuration(min){min=Math.max(0,Math.round(min));const h=Math.floor(min/60),m=min%60;return h?`${h}h ${String(m).padStart(2,'0')}min`:`${m} min`}function fmtClock(d){return d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}function distanceMeters(a,b){const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}function resetStats(){$('routeKm').textContent=$('totalTime').textContent=$('finishTime').textContent=$('serviceTime').textContent='-';routeStats=null;$('startRoute').disabled=true;$('nextStopText').textContent='Otimize ou valide a rota para iniciar'}function phoneHeader(){return headers.find(h=>/(whats|telefone|celular|phone|fone|mobile)/i.test(h))||''}function sequenceHeader(){return headers.find(h=>/^sequence$/i.test(h.trim()))||headers.find(h=>/sequ[eê]ncia|sequence/i.test(h))||''}function importedSequences(stop){const h=sequenceHeader();if(!h||!stop)return[];return stop.rows.map(r=>String(r[h]??'').trim()).filter(v=>v!=='')}function sequenceText(stop){const values=importedSequences(stop);return values.length?`N° Pacote: ${values.join(', ')}`:'N° Pacote: não informado'}function normalizePhone(v){let n=String(v??'').replace(/\D/g,'');if((n.length===10||n.length===11)&&!n.startsWith('55'))n='55'+n;return n.length>=12&&n.length<=13?n:''}function whatsappUrl(row,stopNo){const phone=normalizePhone(row[phoneHeader()]);if(!phone)return'';return`https://wa.me/${phone}?text=${encodeURIComponent(`Olá! Sua entrega está prevista na rota de hoje. Você é a parada ${stopNo}. Endereço: ${row['Destination Address']||''}.`)}`}
function initMap(){if(map)return;map=L.map('map').setView([-23.55,-46.63],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map)}function numberedIcon(n,count,active=false,done=false){return L.divIcon({className:`stop-wrap${active?' active':''}${done?' done':''}`,html:`<div class="stop-pin">${done?'✓':n}</div>${count>1?`<span class="stop-count">${count}</span>`:''}`,iconSize:[34,42],iconAnchor:[17,38]})}function drawPoints(){initMap();markers.forEach(m=>m.remove());markers=[];const seq=order.length?order:stops.map((_,i)=>i);seq.forEach((idx,n)=>markers.push(L.marker([stops[idx].lat,stops[idx].lon],{icon:numberedIcon(n+1,stops[idx].rows.length)}).bindTooltip(`<b>Parada ${n+1}</b><br>${esc(stops[idx].address)}`).addTo(map)));if(currentLocation)markers.push(L.circleMarker([currentLocation.lat,currentLocation.lon],{radius:9,weight:4}).bindTooltip('<b>Local atual / saída</b>').addTo(map));if(stops.length)map.fitBounds(L.latLngBounds([...stops.map(s=>[s.lat,s.lon]),...(currentLocation?[[currentLocation.lat,currentLocation.lon]]:[])]).pad(.12))}
function renderManual(){const seq=order.length?order:stops.map((_,i)=>i);$('manualList').innerHTML=seq.map((idx,n)=>`<div class="manual-stop" draggable="true" data-pos="${n}"><span class="drag">☰</span><b>${n+1}</b><div><strong>${esc(stops[idx].address)}</strong><small>${stops[idx].rows.length} entrega(s)</small></div><button class="move" data-dir="-1" data-pos="${n}">↑</button><button class="move" data-dir="1" data-pos="${n}">↓</button></div>`).join('');$('manualList').querySelectorAll('.manual-stop').forEach(el=>{el.addEventListener('dragstart',()=>dragFrom=Number(el.dataset.pos));el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();moveStop(dragFrom,Number(el.dataset.pos))})});$('manualList').querySelectorAll('.move').forEach(b=>b.addEventListener('click',()=>moveStop(Number(b.dataset.pos),Number(b.dataset.pos)+Number(b.dataset.dir))));$('recalculate').disabled=!order.length}
function moveStop(from,to){const seq=order.length?[...order]:stops.map((_,i)=>i);if(from==null||to<0||to>=seq.length||from===to)return;const x=seq.splice(from,1)[0];seq.splice(to,0,x);order=seq;optimizedRows=flattenRoute(stops,order);resetStats();drawPoints();renderManual();renderColumns();$('export').disabled=true;$('notice').textContent='Ordem alterada. Recalcule antes de iniciar a navegação.'}
function renderColumns(){selectedHeaders=headers.filter((h,i)=>$(`col-${i}`)?.checked);const hs=selectedHeaders,seq=order.length?order:stops.map((_,i)=>i),out=[];$('thead').innerHTML='<th>Rota</th><th>Entrega</th><th>Contato</th>'+hs.map(h=>`<th>${esc(h)}</th>`).join('');seq.forEach((idx,n)=>stops[idx].rows.forEach((r,d)=>out.push({stopNo:n+1,d:d+1,count:stops[idx].rows.length,r})));$('tbody').innerHTML=out.map(x=>{const w=whatsappUrl(x.r,x.stopNo);return`<tr><td class="stopnum"><b>${x.stopNo}</b></td><td>${x.d}/${x.count}</td><td>${w?`<a class="wa" href="${w}" target="_blank" rel="noopener">WhatsApp</a>`:'-'}</td>${hs.map(h=>`<td>${esc(x.r[h]??'')}</td>`).join('')}</tr>`}).join('')}
function buildColumnPicker(){selectedHeaders=[...headers];$('columnOptions').innerHTML=headers.map((h,i)=>`<label><input type="checkbox" id="col-${i}" checked> ${esc(h)}</label>`).join('');$('columnOptions').querySelectorAll('input').forEach(x=>x.addEventListener('change',renderColumns))}
function fillStart(){const options=stops.map((s,i)=>`<option value="${i}">${i+1}. ${esc(s.address)}</option>`).join('');$('start').innerHTML=options}
async function readExcel(file){resumeMode=false;setStatus('Lendo Excel…');filename=file.name;const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{defval:''});headers=rows.length?Object.keys(rows[0]):[];stops=groupStops(rows);order=[];optimizedRows=[];currentLocation=null;$('deliveries').textContent=rows.length;$('stops').textContent=stops.length;$('workspace').hidden=false;fillStart();buildColumnPicker();drawPoints();renderManual();renderColumns();resetStats();$('startRoute').textContent='▶ Iniciar rota';$('routeSummary').textContent=`${stops.length} paradas físicas para ${rows.length} entregas.`;setStatus('Cadastrando locais…');try{const sync=await syncImportedStops(stops);$('notice').textContent=sync.mode==='cloud'?`Planilha carregada. ${stops.length} locais sincronizados com sua conta. A rota em andamento permanece salva até você iniciar uma nova rota.`:`Planilha carregada. ${stops.length} locais cadastrados neste dispositivo. A rota em andamento permanece salva até você iniciar uma nova rota.`}catch(e){$('notice').textContent=`Planilha carregada e salva localmente. A rota em andamento foi preservada; a sincronização com a nuvem ficou pendente: ${e.message}`}setStatus('Planilha pronta')}
async function fetchMatrix(){const d=await routingTable(stops.map(s=>({lat:s.lat,lon:s.lon})));if(d.code!=='Ok'||!d.distances)throw new Error('Matriz viária inválida');return d}
async function optimize(){if(!stops.length)return;setStatus('Otimizando…');$('notice').textContent='Consultando sentidos permitidos e custos reais da malha viária…';try{const data=await fetchMatrix();matrix=data.distances;const start=Number($('start').value||0);order=optimizeOrder(stops,matrix,start,Number($('penalty').value||0));optimizedRows=flattenRoute(stops,order);await calculateRoute();renderManual();renderColumns();$('export').disabled=false;setStatus('Rota pronta')}catch(e){setStatus('Erro');$('notice').textContent=e.message}}
async function calculateRoute(){const seq=order.map(i=>stops[i]),points=[...(currentLocation?[currentLocation]:[]),...seq].map(p=>({lat:p.lat,lon:p.lon})),d=await routingRoute(points,{steps:false});if(d.code!=='Ok'||!d.routes?.[0])throw new Error('Não foi possível validar a rota dirigida.');const route=d.routes[0],service=seq.length*SERVICE_MINUTES,total=route.duration/60+service,finish=new Date(Date.now()+total*60000);routeStats={distance:route.distance,duration:route.duration,total,finish};$('routeKm').textContent=`${(route.distance/1000).toFixed(1)} km`;$('serviceTime').textContent=fmtDuration(service);$('totalTime').textContent=fmtDuration(total);$('finishTime').textContent=fmtClock(finish);$('routeSummary').textContent=`${seq.length} paradas · ${(route.distance/1000).toFixed(1)} km · ${fmtDuration(total)}`;$('notice').textContent='Rota validada pelo gateway viário do RouteFlow. O tempo total inclui cerca de 3 min por parada.';$('startRoute').disabled=false;$('nextStopText').textContent=`Próxima: ${seq[0]?.address||'-'}`;if(routeLine)routeLine.remove();routeLine=L.geoJSON(route.geometry,{style:{weight:5,opacity:.75}}).addTo(map);drawPoints()}
function exportExcel(){if(!routeStats)return;const hs=selectedHeaders,out=optimizedRows.map(r=>{const o={'Optimized Sequence':r['Optimized Sequence'],'Optimized Stop':r['Optimized Stop']};for(const h of hs)o[h]=r[h]??'';return o}),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(out),'Rota Otimizada');XLSX.writeFile(wb,`routeflow-otimizado-${filename.replace(/\.xlsx?$/i,'')}.xlsx`)}
function getPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Geolocalização não disponível.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy}),reject,{enableHighAccuracy:true,timeout:12000,maximumAge:3000})})}
async function useCurrentLocation(){setStatus('Obtendo GPS…');try{currentLocation=await getPosition();drawPoints();resetStats();$('notice').textContent=`Local atual definido como saída. Precisão aproximada: ${Math.round(currentLocation.accuracy)} m.`;setStatus('GPS pronto')}catch(e){setStatus('GPS indisponível');$('notice').textContent='Não foi possível obter o local atual. No celular, abra o RouteFlow por HTTPS e permita a localização.'}}
function initNavMap(){if(navMap)return;navMap=L.map('navMap',{zoomControl:false}).setView([-23.55,-46.63],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(navMap)}
function renderNavStops(){if(!navMap||!order.length)return;navStopMarkers.forEach(m=>m.remove());navStopMarkers=[];order.forEach((idx,n)=>{const s=stops[idx],marker=L.marker([s.lat,s.lon],{icon:numberedIcon(n+1,s.rows.length,n===navigationIndex,n<navigationIndex),zIndexOffset:n===navigationIndex?1200:500}).bindTooltip(`${n<navigationIndex?'Concluída':'Parada '+(n+1)}: ${esc(s.address)}`,{direction:'top'}).addTo(navMap);navStopMarkers.push(marker)})}
function updateNavigationUI(){if(!order.length)return;const s=stops[order[Math.min(navigationIndex,order.length-1)]];$('nextStopText').textContent=`Parada ${navigationIndex+1} de ${order.length}: ${s.address}`;if($('navSequence'))$('navSequence').textContent=`Parada ${navigationIndex+1} de ${order.length}`;if($('navImportedSequence'))$('navImportedSequence').textContent=sequenceText(s);$('nextRoute').disabled=navigationIndex>=order.length-1;if(navMap)renderNavStops()}
function speak(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='pt-BR';speechSynthesis.speak(u)}catch{}}
async function routeToCurrentStop(pos,force=false){if(!order.length)return;const dest=stops[order[navigationIndex]],now=Date.now();if(!force&&lastRerouteAt&&now-lastRerouteAt<REROUTE_COOLDOWN)return;const d=await routingRoute([{lat:pos.lat,lon:pos.lon},{lat:dest.lat,lon:dest.lon}],{steps:true});if(d.code!=='Ok'||!d.routes?.[0])throw new Error('Sem rota até a próxima parada.');const rt=d.routes[0];lastRerouteAt=now;if(navLine)navLine.remove();navLine=L.geoJSON(rt.geometry,{style:{weight:7,opacity:.85}}).addTo(navMap);$('navDistance').textContent=rt.distance>=1000?`${(rt.distance/1000).toFixed(1)} km`:`${Math.round(rt.distance)} m`;$('navEta').textContent=Math.max(1,Math.round(rt.duration/60));$('navArrival').textContent=fmtClock(new Date(Date.now()+rt.duration*1000));$('navDestination').textContent=`${dest.address} · ${dest.rows.length} entrega(s)`;if($('navSequence'))$('navSequence').textContent=`Parada ${navigationIndex+1} de ${order.length}`;if($('navImportedSequence'))$('navImportedSequence').textContent=sequenceText(dest);const steps=rt.legs?.[0]?.steps||[],next=steps.find(s=>s.distance>20)||steps[0];let instruction='Siga pela rota indicada';if(next){const name=next.name||'';instruction=next.maneuver?.type==='turn'?`Vire ${name}`:`Siga ${name}`.trim()}$('navInstruction').textContent=instruction;$('navInstructionDistance').textContent=next?.distance?`em ${Math.round(next.distance)} m`:'';renderNavStops();navMap.fitBounds(L.geoJSON(rt.geometry).getBounds().pad(.18));if(force)speak(`${instruction}. Próxima parada: ${dest.address}`)}
function operationalSnapshot(){const routeStops=order.map(i=>stops[i]).map(s=>({key:s.key,lat:s.lat,lon:s.lon,street:s.street,address:s.address,neighborhood:s.neighborhood,city:s.city,zipcode:s.zipcode,rows:s.rows}));return{version:1,filename,headers,selectedHeaders,stops:routeStops,order:routeStops.map((_,i)=>i),currentLocation,navigationIndex,routeStats:routeStats?{distance:routeStats.distance,duration:routeStats.duration,total:routeStats.total,finish:routeStats.finish instanceof Date?routeStats.finish.toISOString():routeStats.finish}:null,optimizedRows}}
async function persistProgress(){try{await markRouteProgress(navigationIndex,operationalSnapshot())}catch{}}
async function startNavigation(){if(!order.length)return;resumeMode=false;navigationIndex=0;try{await beginRoute({filename,stops,order,routeStats,operational:operationalSnapshot()})}catch(e){$('notice').textContent=`Rota iniciada localmente. Sincronização da rota pendente: ${e.message}`}await openNavigator(true)}
async function openNavigator(forceInstruction=false){if(!order.length)return;initNavMap();$('navigator').hidden=false;document.body.classList.add('navigating');setTimeout(()=>navMap.invalidateSize(),100);updateNavigationUI();renderNavStops();let pos=currentLocation||lastNavPosition;try{pos=await getPosition();lastNavPosition=pos}catch{}if(pos){updateUserMarker(pos);try{await routeToCurrentStop(pos,forceInstruction)}catch(e){$('navInstruction').textContent=e.message}}else{$('navInstruction').textContent='Aguardando GPS para traçar até a próxima parada'}startGpsWatch()}
function updateUserMarker(pos){if(!navMap)return;if(!navMarker)navMarker=L.circleMarker([pos.lat,pos.lon],{radius:9,weight:5,fillOpacity:1}).addTo(navMap);else navMarker.setLatLng([pos.lat,pos.lon]);$('navAccuracy').textContent=`±${Math.round(pos.accuracy||0)} m`;lastNavPosition=pos;const dest=stops[order[navigationIndex]];if(dest&&distanceMeters(pos,dest)<=ARRIVAL_METERS){$('navInstruction').textContent=`Você chegou à parada ${navigationIndex+1}`;$('navInstructionDistance').textContent=dest.address}}
function startGpsWatch(){if(navWatch!=null||!navigator.geolocation)return;navWatch=navigator.geolocation.watchPosition(async p=>{const old=lastNavPosition,pos={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy};updateUserMarker(pos);const moved=old?distanceMeters(old,pos):Infinity;if(moved>30)try{await routeToCurrentStop(pos)}catch{}},{enableHighAccuracy:true,maximumAge:2000,timeout:15000})}
function stopNavigator(){if(navWatch!=null){navigator.geolocation.clearWatch(navWatch);navWatch=null}$('navigator').hidden=true;document.body.classList.remove('navigating');speechSynthesis?.cancel?.()}
async function advanceAfterProof(){if(navigationIndex<order.length-1){navigationIndex++;await persistProgress();updateNavigationUI();if(lastNavPosition)await routeToCurrentStop(lastNavPosition,true);return}await finishRoute();$('nextStopText').textContent='Rota concluída';$('navInstruction').textContent='Todas as paradas foram concluídas';$('navInstructionDistance').textContent='Bom trabalho';$('nextRoute').disabled=true;await persistProgress();speak('Rota concluída')}
async function completeCurrentStop(){await openProof()}async function nextStop(){await openProof()}
async function openProof(){if(!order.length)return;const stop=stops[order[navigationIndex]];proofStatus='DELIVERED';$('proofStop').textContent=`Parada ${navigationIndex+1} de ${order.length} · ${stop.address}`;$('proofRecipient').value='';$('proofFailure').value='';$('proofNotes').value='';$('proofPhoto').value='';$('proofGps').textContent=lastNavPosition?`${lastNavPosition.lat.toFixed(6)}, ${lastNavPosition.lon.toFixed(6)} · ±${Math.round(lastNavPosition.accuracy||0)} m`:'Obtendo localização…';$('proofPackages').innerHTML=stop.rows.map((r,i)=>`<div class="proof-package"><b>Entrega ${i+1}/${stop.rows.length}</b><span>${esc(sequenceText({rows:[r]}))}</span><small>${esc(r['SPX TN']||r['AT ID']||'Pacote sem identificador')}</small></div>`).join('');setProofStatus('DELIVERED');$('proofModal').hidden=false;try{lastNavPosition=await getPosition();$('proofGps').textContent=`${lastNavPosition.lat.toFixed(6)}, ${lastNavPosition.lon.toFixed(6)} · ±${Math.round(lastNavPosition.accuracy||0)} m`}catch{if(!lastNavPosition)$('proofGps').textContent='GPS indisponível — o comprovante será salvo sem coordenadas.'}}
function setProofStatus(status){proofStatus=status;const failed=status==='FAILED';$('proofDelivered').classList.toggle('active',!failed);$('proofFailed').classList.toggle('active',failed);$('failureField').hidden=!failed;$('recipientField').hidden=failed}function closeProof(){$('proofModal').hidden=true}
async function saveProof(){const stop=stops[order[navigationIndex]],failed=proofStatus==='FAILED',reason=$('proofFailure').value.trim();if(failed&&!reason){$('proofFailure').focus();return}const photo=$('proofPhoto').files?.[0],photoName=photo?.name||'',notes=$('proofNotes').value.trim();await recordStopDeliveries({stop,stopNo:navigationIndex+1,totalStops:order.length,position:lastNavPosition,recipient:$('proofRecipient').value.trim(),status:proofStatus,failureReason:failed?reason:'',notes,proofPhotoName:photoName});closeProof();await advanceAfterProof()}
function restoreOperational(saved){const op=saved?.operational;if(!op?.stops?.length||!Array.isArray(op.order))return false;resumeMode=true;filename=op.filename||saved.sourceFilename||'rota-recuperada.xlsx';headers=Array.isArray(op.headers)?op.headers:[];selectedHeaders=Array.isArray(op.selectedHeaders)?op.selectedHeaders:headers;stops=op.stops;order=op.order;currentLocation=op.currentLocation||null;navigationIndex=Math.max(0,Math.min(Number(op.navigationIndex??saved.completedStops??0),order.length-1));optimizedRows=Array.isArray(op.optimizedRows)?op.optimizedRows:flattenRoute(stops,order);const rs=op.routeStats;routeStats=rs?{...rs,finish:rs.finish?new Date(rs.finish):new Date()}:null;rows=stops.flatMap(s=>s.rows||[]);$('deliveries').textContent=rows.length;$('stops').textContent=stops.length;$('workspace').hidden=false;fillStart();buildColumnPicker();headers.forEach((_,i)=>{const el=$(`col-${i}`);if(el)el.checked=selectedHeaders.includes(headers[i])});drawPoints();renderManual();renderColumns();if(routeStats){$('routeKm').textContent=`${(Number(routeStats.distance||0)/1000).toFixed(1)} km`;$('serviceTime').textContent=fmtDuration(stops.length*SERVICE_MINUTES);$('totalTime').textContent=fmtDuration(routeStats.total||0);$('finishTime').textContent=fmtClock(routeStats.finish);$('startRoute').disabled=false}$('routeSummary').textContent=`${stops.length} paradas · rota recuperada`;$('notice').textContent=`Rota em andamento recuperada: ${Math.min(navigationIndex,order.length)}/${order.length} paradas concluídas.`;$('startRoute').textContent='▶ Retomar rota';updateNavigationUI();return true}
async function recoverActiveRoute(){try{const saved=await syncActiveRoute();if(saved&&restoreOperational(saved))setStatus('Rota recuperada')}catch{}}
$('file').addEventListener('change',e=>e.target.files[0]&&readExcel(e.target.files[0]));$('optimize').addEventListener('click',optimize);$('export').addEventListener('click',exportExcel);$('currentLocation').addEventListener('click',useCurrentLocation);$('recalculate').addEventListener('click',calculateRoute);$('startRoute').addEventListener('click',()=>resumeMode?openNavigator(true):startNavigation());$('nextRoute').addEventListener('click',nextStop);$('completeStop').addEventListener('click',completeCurrentStop);$('stopNavigation').addEventListener('click',stopNavigator);$('proofDelivered').addEventListener('click',()=>setProofStatus('DELIVERED'));$('proofFailed').addEventListener('click',()=>setProofStatus('FAILED'));$('closeProof').addEventListener('click',closeProof);$('saveProof').addEventListener('click',saveProof);$('allColumns').addEventListener('click',()=>{$('columnOptions').querySelectorAll('input').forEach(x=>x.checked=true);renderColumns()});$('noColumns').addEventListener('click',()=>{$('columnOptions').querySelectorAll('input').forEach(x=>x.checked=false);renderColumns()});initMap();initAuthUI();initRegistryUI();initDeliveryHistoryUI();initRouteHistoryUI();initMobileUI();recoverActiveRoute();
