import{syncAddressEdit}from'./sync.js';
const REGISTRY_KEY='routeflow.addressRegistry.v1';
const $=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=s=>String(s||'').trim().toLocaleLowerCase('pt-BR').replace(/\s+/g,' ');
const read=()=>{try{return JSON.parse(localStorage.getItem(REGISTRY_KEY)||'{}')}catch{return{}}};
const addresses=()=>[...document.querySelectorAll('#start option')].map(o=>o.textContent.replace(/^\d+\.\s*/,''));
const currentAddress=()=>($('navDestination')?.textContent||'').split(' · ')[0].trim();
function syncNav(){const r=read()[key(currentAddress())];if($('navPlaceInfo'))$('navPlaceInfo').textContent=`Local: ${r?.type||'Casa'}${r?.hours?' · '+r.hours:''}`;if($('navPackageSize'))$('navPackageSize').textContent=`Volume: ${r?.size||'não informado'}`}
function render(){const values=Object.values(read()).sort((a,b)=>(b.lastImportedAt||b.updatedAt||'').localeCompare(a.lastImportedAt||a.updatedAt||''));$('registryList').innerHTML=values.length?values.map(r=>`<article class="registry-item"><strong>${safe(r.address)}</strong><span>${safe(r.type||'Casa')} · Volume ${safe(r.size||'não informado')}</span><small>${r.hours?'Horário: '+safe(r.hours):'Horário não informado'} · Importado ${Number(r.importCount)||1} vez(es)${r.access?' · '+safe(r.access):''}</small></article>`).join(''):'<div class="history-empty">Nenhum endereço cadastrado ainda.</div>'}
function load(){const r=read()[key($('registryAddress').value)]||{type:'Casa'};$('registryType').value=r.type||'Casa';$('registryHours').value=r.hours||'';$('registrySize').value=r.size||'';$('registryAccess').value=r.access||'';$('registryParking').value=r.parking||'';$('registryNotes').value=r.notes||''}
export function populateRegistryAddresses(){const list=addresses();$('registryAddress').innerHTML=list.length?list.map(a=>`<option>${safe(a)}</option>`).join(''):'<option value="">Importe uma rota primeiro</option>';load()}
export function initRegistryUI(){const route=$('navSequence'),imported=$('navImportedSequence');if(route&&imported){const split=()=>{const text=route.textContent||'',marker=' · Sequence da planilha:',pos=text.indexOf(marker);if(pos>=0){const value=text.slice(pos+marker.length).trim();route.textContent=text.slice(0,pos);imported.textContent=`N° Pacote: ${value||'não informado'}`}syncNav()};new MutationObserver(split).observe(route,{childList:true,characterData:true,subtree:true});new MutationObserver(syncNav).observe($('navDestination'),{childList:true,characterData:true,subtree:true});split()}$('registryAddress').addEventListener('change',load);$('saveRegistry').addEventListener('click',async()=>{const address=$('registryAddress').value;if(!address||address==='Importe uma rota primeiro')return;const patch={type:$('registryType').value||'Casa',hours:$('registryHours').value.trim(),size:$('registrySize').value,access:$('registryAccess').value.trim(),parking:$('registryParking').value.trim(),notes:$('registryNotes').value.trim()};try{await syncAddressEdit(address,patch);render();syncNav();alert('Informações do endereço atualizadas.')}catch(e){render();syncNav();alert(`Alterações salvas neste dispositivo. Sincronização pendente: ${e.message}`)}});new MutationObserver(()=>{populateRegistryAddresses();render()}).observe($('start'),{childList:true});window.addEventListener('routeflow:registry-synced',()=>{render();load();syncNav()});populateRegistryAddresses();render()}
