import{apiBase,hasSession,createRoute,updateRoute,getActiveRoute}from'./api.js';
import{saveLocalRoute,cancelOtherActiveRoutes}from'./route-history-ui.js';
const KEY='routeflow.activeRoute.v1';
const enabled=()=>Boolean(apiBase()&&hasSession());
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const write=v=>{localStorage.setItem(KEY,JSON.stringify(v));window.dispatchEvent(new CustomEvent('routeflow:active-route-synced',{detail:v}))};
const fromRemote=r=>r?{clientId:r.clientId||`server-${r.id}`,serverId:r.id,sourceFilename:r.sourceFilename,status:r.status,startedAt:r.startedAt,finishedAt:r.finishedAt,plannedKm:r.plannedKm,plannedMinutes:r.plannedMinutes,stops:r.stops,deliveries:r.deliveriesCount,completedStops:r.completedStops||0,operational:r.operational,updatedAt:r.updatedAt}:null;
export function activeRoute(){return read()}
export function resumableRoute(){const route=read();return route?.status==='ACTIVE'?route:null}
export async function syncActiveRoute(){if(!enabled())return read();try{const remote=await getActiveRoute();if(!remote)return read();const cloud=fromRemote(remote),local=read();if(local?.clientId===cloud.clientId)cloud.completedStops=Math.max(Number(local.completedStops||0),Number(cloud.completedStops||0));write(cloud);saveLocalRoute(cloud);return cloud}catch{return read()}}
export async function beginRoute({sourceFilename,plannedKm,plannedMinutes,stops,deliveries,operational}){const previous=read();if(previous?.status==='ACTIVE'){previous.status='CANCELLED';previous.finishedAt=new Date().toISOString();saveLocalRoute(previous);if(enabled()&&previous.serverId)updateRoute(previous.serverId,{status:'CANCELLED',finishedAt:previous.finishedAt}).catch(()=>{})}cancelOtherActiveRoutes();const startedAt=new Date().toISOString(),local={clientId:`route-${Date.now()}-${Math.random().toString(36).slice(2)}`,sourceFilename,status:'ACTIVE',startedAt,plannedKm,plannedMinutes,stops,deliveries,completedStops:0,operational};write(local);saveLocalRoute(local);if(enabled()){try{const remote=await createRoute({clientId:local.clientId,sourceFilename,startedAt,plannedKm,plannedMinutes,stops,deliveriesCount:deliveries,completedStops:0,operational});local.serverId=remote.id;local.updatedAt=remote.updatedAt;write(local);saveLocalRoute(local)}catch{}}return local}
export async function markRouteProgress(completedStops){const route=read();if(!route)return null;route.completedStops=completedStops;write(route);saveLocalRoute(route);if(enabled()&&route.serverId){try{const remote=await updateRoute(route.serverId,{completedStops,operational:route.operational});route.updatedAt=remote.updatedAt;write(route);saveLocalRoute(route)}catch{}}return route}
export async function finishRoute(){const route=read();if(!route)return null;route.status='COMPLETED';route.finishedAt=new Date().toISOString();write(route);saveLocalRoute(route);if(enabled()&&route.serverId){try{await updateRoute(route.serverId,{status:'COMPLETED',finishedAt:route.finishedAt,completedStops:route.completedStops,operational:route.operational})}catch{}}return route}
export function clearActiveRoute(){localStorage.removeItem(KEY)}
